
import os
import glob
import pandas as pd
import argparse
import xml.etree.ElementTree as ET
from cloudmesh.common.util import path_expand
from cloudmesh.common.Shell import Shell


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given
       directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """

    xml_list = []
    for xml_file in glob.glob(path + '/*.xml'):
        tree = ET.parse(xml_file)
        root = tree.getroot()
        for member in root.findall('object'):
            value = (root.find('filename').text,
                    int(root.find('size')[0].text),
                    int(root.find('size')[1].text),
                    member[0].text,
                    int(member[4][0].text),
                    int(member[4][1].text),
                    int(member[4][2].text),
                    int(member[4][3].text)
                    )
            xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


class XmlToCSV():

    inputDir_train = path_expand('~/.cloudmesh/secchi/images/train')
    inputDir_test = path_expand('~/.cloudmesh/secchi/images/test')
    def __init__(self, outputDir = '~/.cloudmesh/secchi/TFrecord'):

        self.outputDir = path_expand(outputDir)
        Shell.mkdir(self.outputDir)

    def xml_csv_conv(self):

        xml_df = xml_to_csv(self.inputDir_train)
        xml_df.to_csv(os.path.join(self.outputDir,'train_labels.csv'), index=None)
        print('Successfully converted train xml to csv.')

        xml_df = xml_to_csv(self.inputDir_test)
        xml_df.to_csv(os.path.join(self.outputDir, 'test_labels.csv'), index=None)
        print('Successfully converted train xml to csv.')


