VERSION=1.3.0

download:
	@mkdir -p ../build
	# cd ../tensoflow; wget xyz-$(VERSION).tgz
	# cd ../tensoflow; tar xvf xyz.tgz
	@echo "do what is needed"

deploy:
	@cp predict.py ../build/predict.py

run:
	echo "do what is needed to run"